# Generated by Django 4.2.30 on 2026-07-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_full_name_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullName',
            new_name='full_Name',
        ),
    ]
