# Generated by Django 4.2.30 on 2026-07-30 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_fullname_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_Name',
            new_name='full_name',
        ),
    ]
